
# Install required packages
- name: install packages
  yum: pkg={{item}} state=present
  with_items:
    - rabbitmq-server

- name: make sure mysql is running
  service: name=rabbitmq-server state=started

- name: fetch list of users
  command: rabbitmqctl list_users
  register: _users

- name: add openstack user to rabbitmq
  command: rabbitmqctl add_user openstack {{ openstack.admin_password }}
  when: "'openstack' not in _users.stdout"

- name: add openstack permissions to rabbitmq
  command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
